### Nama : Gabriella Caesaria Vianney
### NIM : 2209106007
### Kelas : A1 2022

## **POSTTEST 2**

In [1]:
import pandas as pd
import prettytable as prtl
gaby = pd.read_csv('cleaned_all_phones.csv')
gaby.describe()

,inches,battery,ram(GB),weight(g),storage(GB),price(USD)
count,1512.000000,1512.000000,1512.000000,1512.000000,1512.000000,1512.000000
mean,6.422460,4389.798942,6.683862,187.636243,109.164683,337.847036
std,0.477043,784.607022,2.701433,26.200115,74.436484,266.740821
min,3.800000,1821.000000,1.000000,130.000000,1.000000,40.000000
25%,6.300000,4000.000000,4.000000,175.000000,64.000000,179.997500
50%,6.500000,4500.000000,8.000000,187.000000,128.000000,260.000000
75%,6.670000,5000.000000,8.000000,197.250000,128.000000,400.000000
max,10.400000,7250.000000,24.000000,500.000000,512.000000,2300.000000

##### 1. Menampilkan rata-rata, standar deviasi, nilai minimum, nilai maksimum, Q1, Q2, dan Q3 dari attribute bertipe angka

In [5]:
gaby.select_dtypes(['int64', 'float64']).head(10)

   inches  battery  ram(GB)  weight(g)  storage(GB)  price(USD)
0     5.0     2200        2      140.0           16       120.0
1     5.3     2700        2      140.0           16       100.0
2     5.2     3000        4      147.0           16       420.0
3     5.5     4100        4      165.0           32       150.0
4     5.1     3200        4      145.0           32       420.0
5     5.0     2300        3      143.0           32       140.0
6     5.2     3000        4      146.0           32       420.0
7     5.5     3750        6      165.0           64       170.0
8     6.0     2700        4      188.0           32       250.0
9     5.5     4500        2      164.0           16       170.0

##### 2. Menampilkan 10 record pertama dari dataset dengan attribute bertipe angka

In [10]:
data = {}

data['Jumlah Record'] = gaby.shape[0]
data['Jumlah Atribut'] = gaby.shape[1]
data['Nama Atribut'] = gaby.columns.tolist()
data['Jumlah Atribut Dengan Tipe Angka'] = gaby.select_dtypes(['int64', 'float64']).shape[1]

dict = list(data.keys())

tab = prtl.PrettyTable()

tab.add_column(dict[0], [data['Jumlah Record']])
tab.add_column(dict[1], [data['Jumlah Atribut']])
tab.add_column(dict[2], ['\n'.join(data['Nama Atribut'])])
tab.add_column(dict[3], [data['Jumlah Atribut Dengan Tipe Angka']])

print(tab)

+---------------+----------------+-------------------+----------------------------------+
| Jumlah Record | Jumlah Atribut |    Nama Atribut   | Jumlah Atribut Dengan Tipe Angka |
+---------------+----------------+-------------------+----------------------------------+
|      1512     |       22       |     phone_name    |                6                 |
|               |                |       brand       |                                  |
|               |                |         os        |                                  |
|               |                |       inches      |                                  |
|               |                |     resolution    |                                  |
|               |                |      battery      |                                  |
|               |                |    battery_type   |                                  |
|               |                |      ram(GB)      |                                  |
|               |                | announcement_date |                                  |
|               |                |     weight(g)     |                                  |
|               |                |    storage(GB)    |                                  |
|               |                |     video_720p    |                                  |
|               |                |    video_1080p    |                                  |
|               |                |      video_4K     |                                  |
|               |                |      video_8K     |                                  |
|               |                |    video_30fps    |                                  |
|               |                |    video_60fps    |                                  |
|               |                |    video_120fps   |                                  |
|               |                |    video_240fps   |                                  |
|               |                |    video_480fps   |                                  |
|               |                |    video_960fps   |                                  |
|               |                |     price(USD)    |                                  |
+---------------+----------------+-------------------+----------------------------------+

##### 3. Menampilkan informasi jumlah record, jumlah attribute, nama attribute, jumlah attribute dengan tipe angka dengan menggunakan dictionary

In [13]:
gaby.iloc[7:, 3:]

,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),storage(GB),video_720p,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
7,5.50,1440x2560,3750,Li-Ion,6,2017-02-01,165.0,64,True,True,True,False,True,True,False,False,False,False,170.000
8,6.00,1080x1920,2700,Li-Ion,4,2017-02-01,188.0,32,False,True,False,False,True,False,False,False,False,False,250.000
9,5.50,720x1280,4500,Li-Ion,2,2017-02-01,164.0,16,True,True,False,False,True,False,False,False,False,False,170.000
10,5.50,1080x1920,4100,Li-Po,4,2017-02-01,165.0,16,True,True,False,False,True,False,True,False,False,False,130.000
11,5.20,1080x1920,2900,Li-Ion,4,2017-02-27,161.0,32,True,True,True,False,True,True,False,False,False,True,220.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,6.64,1080x2388,5000,Li-Po,8,2023-08-18,190.0,256,False,True,False,False,True,False,False,False,False,False,170.000
1508,6.72,1080x2400,5000,Li-Po,8,2023-08-23,190.0,128,False,True,False,False,True,False,False,False,False,False,182.880
1509,6.74,1240x2772,5240,Li-Po,16,2023-08-28,205.0,256,True,True,True,False,False,True,False,False,False,False,380.000
1510,6.74,1240x2772,4600,Li-Po,24,2023-08-28,205.0,1,True,True,True,False,False,True,False,False,False,False,470.000
1511,6.78,1080x2400,4600,Li-Po,8,2023-08-31,175.0,128,True,True,True,False,True,False,False,False,False,False,287.988

In [16]:
gaby.loc[7:, 'inches':]

,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),storage(GB),video_720p,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
7,5.50,1440x2560,3750,Li-Ion,6,2017-02-01,165.0,64,True,True,True,False,True,True,False,False,False,False,170.000
8,6.00,1080x1920,2700,Li-Ion,4,2017-02-01,188.0,32,False,True,False,False,True,False,False,False,False,False,250.000
9,5.50,720x1280,4500,Li-Ion,2,2017-02-01,164.0,16,True,True,False,False,True,False,False,False,False,False,170.000
10,5.50,1080x1920,4100,Li-Po,4,2017-02-01,165.0,16,True,True,False,False,True,False,True,False,False,False,130.000
11,5.20,1080x1920,2900,Li-Ion,4,2017-02-27,161.0,32,True,True,True,False,True,True,False,False,False,True,220.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,6.64,1080x2388,5000,Li-Po,8,2023-08-18,190.0,256,False,True,False,False,True,False,False,False,False,False,170.000
1508,6.72,1080x2400,5000,Li-Po,8,2023-08-23,190.0,128,False,True,False,False,True,False,False,False,False,False,182.880
1509,6.74,1240x2772,5240,Li-Po,16,2023-08-28,205.0,256,True,True,True,False,False,True,False,False,False,False,380.000
1510,6.74,1240x2772,4600,Li-Po,24,2023-08-28,205.0,1,True,True,True,False,False,True,False,False,False,False,470.000
1511,6.78,1080x2400,4600,Li-Po,8,2023-08-31,175.0,128,True,True,True,False,True,False,False,False,False,False,287.988

##### 4. Menampilkan nilai dataset pada baris ke-7 hingga data terakhir dan kolom ke-4 hingga kolom terakhir menggunakan ke 2 metode slice

In [18]:
listobject = gaby.select_dtypes(['object']).columns.tolist()
listobject.pop(0)

for i in listobject:
    print(gaby[i].value_counts())

Xiaomi     264
Oppo       213
Samsung    206
Vivo       168
Realme     157
Huawei     137
Honor      124
LG          75
OnePlus     47
Lenovo      43
Sony        37
Apple       22
Google      19
Name: brand, dtype: int64
Android 11                322
Android 10                317
Android 12                233
Android 9.0               210
Android 13                154
Android 8.1                83
Android 8.0                55
Android 7.0                33
Android 7.1.1              17
Android 7.1                14
Android 7.1.2              13
EMUI 12                     6
Android 6.0                 6
Android 8.1 Oreo            5
iOS 16                      4
iOS 15                      4
iOS 14.1                    4
iOS 13                      4
iOS 12                      3
Android 6                   3
Android                     3
Android 12 or 13            2
Android 5.1                 2
Android 9.0 Pie             2
Android 8.0 Oreo            2
Android 6.0.1               2
EMUI 13                     2
Android 10/ Android 11      1
iOS 15.4                    1
iOS 11.1.1                  1
iOS 11                      1
Android 12L                 1
Tizen 3.0                   1
Android 7.0.1               1
Name: os, dtype: int64
1080x2400    437
720x1600     175
1080x2340    171
1080x2408     69
720x1520      47
            ...
1200x2000      1
1224x2664      1
720x1640       1
1860x2480      1
2156x2344      1
Name: resolution, Length: 85, dtype: int64
Li-Po     1242
Li-Ion     270
Name: battery_type, dtype: int64
2018-05-01    20
2018-03-01    16
2019-09-01    16
2018-10-01    15
2019-04-01    14
              ..
2021-02-04     1
2021-02-02     1
2021-01-27     1
2021-01-25     1
2023-08-31     1
Name: announcement_date, Length: 665, dtype: int64

##### 5. Menampilkan jumlah nilai dari semua attribute yang bernilai object, yaitu Brand, OS, Resolution, Battery Type, dan Announcement Date